import = [
"~/.config/alacritty/themes/tokyo-night.toml"
]


[font]
size= 16.0
normal = { family = "JetBrainsMonoNL Nerd Font",  style = "Regular" }

[window]
opacity = 0.75
blur = true
option_as_alt = "OnlyLeft"
