import = [
"~/.config/alacritty/themes/tokyo-night.toml"
]

[font]
size= 16.0
normal = { family = "JetBrainsMonoNL Nerd Font",  style = "Regular" }

[window]
opacity = 0.75
blur = true
option_as_alt = "OnlyLeft"
decorations = "Buttonless"
dynamic_padding = true 
dynamic_title = false 
# resize_increments = true
decorations_theme_variant = "Dark"
title = ""
padding = { x = 0, y = 10 }

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
